version: "3.9"
services:
  # Backend: Spring Boot
  portfolio-backend:
    image: portfolio-backend
   # container_name: portfolio-backend
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: HelloWorld!
      MYSQL_PORT: 3306
    ports:
      - "8080:8080"
  # Frontend: React
  portfolio-frontend:
    image: portfolio-frontend
    container_name: portfolio-frontend
    restart: always
    depends_on:
      - portfolio-backend
    ports:
      - "3001:3001"
  # Database: MySQL
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HelloWorld!
      MYSQL_DATABASE: predictiondb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      retries: 3
      timeout: 5s
      interval: 5s